import { Octokit } from '@octokit/rest';
import { GoogleGenerativeAI } from '@google/generative-ai';
import dotenv from 'dotenv';

dotenv.config();

// Initialize clients
const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN
});

// Initialize Google Gemini AI (Free tier available)
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

// Configuration from environment
const config = {
  prNumber: parseInt(process.env.PR_NUMBER),
  repoOwner: process.env.REPO_OWNER,
  repoName: process.env.REPO_NAME,
  baseSha: process.env.BASE_SHA,
  headSha: process.env.HEAD_SHA
};

/**
 * Fetch PR diff from GitHub
 */
async function getPRDiff() {
  try {
    const { data } = await octokit.pulls.get({
      owner: config.repoOwner,
      repo: config.repoName,
      pull_number: config.prNumber,
      mediaType: {
        format: 'diff'
      }
    });
    return data;
  } catch (error) {
    console.error('Error fetching PR diff:', error.message);
    throw error;
  }
}

/**
 * Fetch PR files changed
 */
async function getPRFiles() {
  try {
    const { data } = await octokit.pulls.listFiles({
      owner: config.repoOwner,
      repo: config.repoName,
      pull_number: config.prNumber
    });
    return data;
  } catch (error) {
    console.error('Error fetching PR files:', error.message);
    throw error;
  }
}

/**
 * Analyze code using Google Gemini AI (Free)
 */
async function analyzeCodeWithAI(diff, files) {
  const filesSummary = files.map(f => ({
    filename: f.filename,
    status: f.status,
    additions: f.additions,
    deletions: f.deletions,
    changes: f.changes
  }));

  const prompt = `You are an expert code reviewer with deep knowledge of software engineering best practices, security, and performance optimization.

Analyze the following pull request changes and provide a comprehensive review.

Files Changed:
${JSON.stringify(filesSummary, null, 2)}

Diff:
${diff.substring(0, 8000)} ${diff.length > 8000 ? '... (truncated for length)' : ''}

Please provide:
1. **Summary**: Brief overview of the changes
2. **Code Quality**: Assessment of code quality, best practices, and potential issues
3. **Security Concerns**: Any security vulnerabilities or concerns
4. **Performance**: Performance implications
5. **Suggestions**: Specific improvement suggestions with line references where applicable
6. **Overall Rating**: Rate the PR (Approve, Request Changes, or Comment)

Format your response in markdown with clear sections.`;

  try {
    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error('Error analyzing code with AI:', error.message);
    throw error;
  }
}

/**
 * Post review comment on PR
 */
async function postReviewComment(reviewContent) {
  try {
    await octokit.issues.createComment({
      owner: config.repoOwner,
      repo: config.repoName,
      issue_number: config.prNumber,
      body: `## 🤖 AI Code Review\n\n${reviewContent}\n\n---\n*This review was automatically generated by AI. Please use your judgment when addressing the feedback.*`
    });
    console.log('Review comment posted successfully');
  } catch (error) {
    console.error('Error posting review comment:', error.message);
    throw error;
  }
}

/**
 * Post inline comments on specific lines
 */
async function postInlineComments(files, suggestions) {
  // This is a placeholder for posting inline comments
  // You can enhance this to parse suggestions and post them on specific lines
  console.log('Inline comments feature can be enhanced based on AI suggestions');
}

/**
 * Main execution
 */
async function main() {
  try {
    console.log('Starting PR review...');
    console.log(`PR #${config.prNumber} in ${config.repoOwner}/${config.repoName}`);

    // Fetch PR data
    console.log('Fetching PR diff and files...');
    const [diff, files] = await Promise.all([
      getPRDiff(),
      getPRFiles()
    ]);

    console.log(`Found ${files.length} changed files`);

    // Analyze with AI
    console.log('Analyzing code with AI...');
    const review = await analyzeCodeWithAI(diff, files);

    // Post review
    console.log('Posting review comment...');
    await postReviewComment(review);

    console.log('PR review completed successfully! ✅');
  } catch (error) {
    console.error('Failed to complete PR review:', error);
    process.exit(1);
  }
}

// Run the main function
main();

// Made with Bob
